# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  #
  # Trying to fix login problem
  #
 
  config.ssh.insert_key = false

  #
  # Disable auto-update of VirtualBox Guest Additions
  #
  config.vbguest.auto_update = false  
  
  #
  # Setup VM Box Name and Location
  #
  config.vm.box = "uvvm_development"
  config.vm.box_url = "http://downloads.bitvis.no/internal/centos-7.0-x86_64-modelsim_ase-10.3d.box"

  #
  # Setup synchronized folders
  #
  config.vm.synced_folder "./", "/home/vagrant/workspace/bitvis_vip_avalon_mm/"

  #
  # Setup Oracle VirtualBox
  # 
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

end